# Generated by Django 5.0.7 on 2024-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kategori_remove_product_product_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='kategori_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
